YesWeScan\YesWeScanBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pseudo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        dateinscription:
            type: datetime
            nullable: false
            comment: ''
            column: dateInscription
        droit:
            type: boolean
            nullable: true
            comment: ''
        password:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
