parameters:
#    yes_we_scan.example.class: YesWeScan\YesWeScanBundle\Example

services:
#    yes_we_scan.example:
#        class: %yes_we_scan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
